apply plugin: 'com.android.application'

android {
    compileSdk 35

    defaultConfig {
        applicationId "com.github.naofum.gogakudroid"
        minSdkVersion 21
        targetSdkVersion 35
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    
    namespace 'com.github.naofum.gogakudroid'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.gms:play-services-ads:23.3.0'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    // build.gradle の dependencies に以下を追加
    implementation 'com.github.Sahad2701:ffmpeg-kit:flutter_fix_retired_v5.1.0'
}
